var searchData=
[
  ['a_20architecture_20support_0',['A architecture support',['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/GCC/ARM_AARCH64/README.md#autotoc_md18',1,'Armv8-A architecture support'],['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/GCC/ARM_AARCH64_SRE/README.md#autotoc_md20',1,'Armv8-A architecture support']]],
  ['additional_20examples_1',['Additional examples',['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/examples/README.md#autotoc_md6',1,'']]],
  ['advanced_20configuration_2',['Advanced Configuration',['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2040/README.md#autotoc_md35',1,'Advanced Configuration'],['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2350_ARM_NTZ/README.md#autotoc_md40',1,'Advanced Configuration'],['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2350_RISC-V/README.md#autotoc_md45',1,'Advanced Configuration']]],
  ['alone_20cloning_20this_20repository_3',['Consuming stand-alone - Cloning this repository',['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/README.md#autotoc_md57',1,'']]],
  ['and_20formatting_4',['Spelling and Formatting',['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/README.md#autotoc_md62',1,'']]],
  ['arc_5fem_5fhs_5',['ThirdParty/GCC/ARC_EM_HS',['../md__d_1_2_projects_2_raspberrypi__pico_2pico__freertos__final_2freertos__pico2_2pico__freertos_26f3fac4393293bc0254a0afa252a9f02.html#autotoc_md48',1,'']]],
  ['architecture_20support_6',['architecture support',['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/GCC/ARM_AARCH64/README.md#autotoc_md18',1,'Armv8-A architecture support'],['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/GCC/ARM_AARCH64_SRE/README.md#autotoc_md20',1,'Armv8-A architecture support']]],
  ['arm_5faarch64_20port_7',['ARM_AARCH64 port',['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/GCC/ARM_AARCH64/README.md#autotoc_md19',1,'']]],
  ['arm_5faarch64_5fsre_20port_8',['ARM_AARCH64_SRE port',['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/GCC/ARM_AARCH64_SRE/README.md#autotoc_md21',1,'']]],
  ['arm_5fca53_5f64_5fbit_20port_9',['ARM_CA53_64_BIT port',['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/GCC/ARM_CA53_64_BIT/README.md#autotoc_md22',1,'']]],
  ['arm_5fca53_5f64_5fbit_5fsre_20port_10',['ARM_CA53_64_BIT_SRE port',['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/GCC/ARM_CA53_64_BIT_SRE/README.md#autotoc_md23',1,'']]],
  ['armv8_20a_20architecture_20support_11',['Armv8 A architecture support',['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/GCC/ARM_AARCH64/README.md#autotoc_md18',1,'Armv8-A architecture support'],['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/GCC/ARM_AARCH64_SRE/README.md#autotoc_md20',1,'Armv8-A architecture support']]],
  ['armv8_20m_12',['Armv8 M',['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2350_ARM_NTZ/README.md#autotoc_md39',1,'FreeRTOS configuration for Armv8-M'],['../D:/Projects/Raspberrypi_pico/pico_freertos_final/freertos_pico2/pico_freertos/FreeRTOS-Kernel/portable/ThirdParty/GCC/RP2350_RISC-V/README.md#autotoc_md44',1,'FreeRTOS configuration for Armv8-M']]]
];
